s = input('Введите первый список:')   
f = input('Введите второй список:')  
ss = set(s)  
fs = set(f)  
print('Пересекающиеся символы:')
print(ss.intersection(fs))
print('Все использующиеся символы:')
print(ss.union(fs))         
print('Непересекающиеся символы:')
print(ss.union(fs) - ss.intersection(fs))  
